name: Deploy dns-updater to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'dns-updater/**'
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './dns-updater'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/melvyndekort/dns-updater:latest
          docker push ghcr.io/melvyndekort/dns-updater:latest
