name: Deploy dns-updater to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'dns-updater/**'
      - '.github/workflows/dns-updater.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './dns-updater'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v5

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push DNS Updater Image'
        uses: docker/build-push-action@v5
        with:
          context: ./dns-updater
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/melvyndekort/dns-updater:latest
